[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    
    # Open Graph Default Tags
    og:type = "website"
    og:url = "https://exaaa.netlify.app"
    og:title = "Exxaa - Your Platform"
    og:description = "Discover, Connect, Trade"
    og:image = "https://exaaa.netlify.app/default-og-image.jpg"